/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming-pc.glb --transform 
Files: gaming-pc.glb [10.19MB] > E:\Brocamp\Projects\My-Portfolio\public\models\gaming-pc-transformed.glb [1.19MB] (88%)
Author: ws12x1 (https://sketchfab.com/ws12x1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-pc-364175250e8847998d0135c357d8b60d
Title: Gaming-pc
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PcModel(props) {
  const { nodes, materials } = useGLTF('/models/gaming-pc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.018']} position={[-0.095, -0.001, 0.244]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.576, 0.041, 1.142]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.018_0']} position={[-0.134, 0.312, -0.552]} scale={[0.271, 0.246, 0.14]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} position={[0.116, 0.08, -0.41]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.004, 0.01]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.maxresdefault_1} position={[0.14, 0.451, -0.555]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.169} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.018_1']} position={[-0.258, 0.35, -0.688]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.139, 0.166, 0.001]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.018_2']} position={[-0.15, 0.123, -0.567]} scale={[0.251, 0.054, 0.115]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.018_3']} position={[-0.405, 0.445, -0.659]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.041, 0.05, 0.048]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.maxresdefault_1_0} position={[-0.368, 0.449, -0.662]} rotation={[Math.PI / 2, 0.651, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.023']} position={[-0.258, 0.35, -0.688]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.139, 0.166, 0.001]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.024']} position={[-0.258, 0.35, -0.688]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.139, 0.166, 0.001]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.018_4']} position={[-0.066, 0.557, -0.553]} rotation={[0, 0, Math.PI]} scale={[0.156, 0.156, 0.209]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.maxresdefault_1_1} position={[-0.15, 0.423, -0.673]} scale={[-0.002, 0.069, 0.017]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Material.018_5']} position={[-0.149, 0.423, -0.675]} scale={[-0.002, 0.069, 0.015]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['Material.018_6']} position={[-0.331, 0.124, -0.465]} scale={[0.055, 0.032, 0.008]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.maxresdefault_1_2} position={[-0.146, 0.13, -0.451]} rotation={[Math.PI / 2, 0, 0]} scale={0.058} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.maxresdefault_1_3} position={[0.137, 0.131, -0.555]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.062} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.PaletteMaterial002} position={[-0.264, 0.179, -0.112]} rotation={[0, 0, -1.554]} scale={[0.03, 0.004, 0.03]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['Material.018_7']} position={[0.001, 0.11, -0.451]} rotation={[Math.PI / 2, 0, 0]} scale={0.071} />
      <mesh geometry={nodes.Object_128.geometry} material={materials['Material.018_8']} position={[-0.406, 0.122, -0.551]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.093} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['Material.018_9']} position={[0.11, 0.557, -0.452]} rotation={[0, Math.PI / 2, 0]} scale={0.011} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.maxresdefault_1_4} position={[-0.252, 0.419, -0.575]} scale={[0.027, 0.063, 0.062]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['Material.018_10']} position={[-0.252, 0.419, -0.575]} scale={[0.027, 0.063, 0.062]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.maxresdefault_1_5} position={[-0.252, 0.419, -0.576]} rotation={[0, 0, -Math.PI / 2]} scale={[0.051, 0.053, 0.051]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.PaletteMaterial003} position={[-0.224, 0.391, -0.508]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.004} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.maxresdefault_1_7} position={[-0.181, 0.235, -0.679]} rotation={[Math.PI / 2, 0, 0]} scale={0.055} />
      <mesh geometry={nodes.Object_174.geometry} material={materials['Material.018_11']} position={[-0.327, 0.288, -0.578]} scale={[0.057, 0.017, 0.06]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials['Material.018_12']} position={[-0.194, 0.288, -0.578]} scale={[0.057, 0.017, 0.06]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials['Material.018_13']} position={[0.183, 0.04, -0.046]} scale={[0.194, 0.187, 0.241]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.PaletteMaterial004} position={[-0.358, 0.32, -0.493]} rotation={[Math.PI / 2, 0, 0]} scale={[0.016, 0.017, 0.016]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials['Material.018_14']} position={[-0.199, 0.312, -0.578]} scale={[0.2, 0.02, 0.082]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials['Material.018_15']} position={[-0.191, 0.334, -0.578]} scale={[0.208, 0.001, 0.085]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.maxresdefault_1_8} position={[-0.285, 0.284, -0.493]} rotation={[Math.PI / 2, 0, 0]} scale={[0.013, 0.014, 0.013]} />
      <mesh geometry={nodes.Object_210.geometry} material={materials['Material.018_16']} position={[0.174, 0.051, -0.043]} rotation={[0, 0, -Math.PI]} scale={[-0.067, 0.036, 0.067]} />
      <mesh geometry={nodes.Object_224.geometry} material={materials['Material.018_17']} position={[-0.403, 0.305, -0.58]} scale={[0.002, 0.028, 0.082]} />
      <mesh geometry={nodes.Object_244.geometry} material={materials['Material.018_18']} position={[0.202, 0.073, -0.043]} rotation={[Math.PI / 2, 1.287, -Math.PI / 2]} scale={0.019} />
      <mesh geometry={nodes.Object_282.geometry} material={materials['Material.018_19']} position={[-0.222, 0.257, 0.93]} rotation={[1.587, 0.121, 1.31]} scale={0.126} />
      <mesh geometry={nodes.Object_286.geometry} material={materials['Material.018_20']} position={[-0.24, 0.304, 0.13]} rotation={[1.576, 0.129, 1.57]} scale={0.176} />
      <mesh geometry={nodes.Object_288.geometry} material={materials.maxresdefault_1_9} position={[-0.213, 0.468, 0.469]} rotation={[Math.PI / 2, 0.07, -Math.PI / 2]} scale={[0.518, 0.518, 0.543]} />
      <mesh geometry={nodes.Object_290.geometry} material={materials['Material.018_21']} position={[-0.252, 0.702, 0.128]} rotation={[Math.PI / 2, 0.07, Math.PI / 2]} scale={0.037} />
      <mesh geometry={nodes.Object_308.geometry} material={materials.PaletteMaterial005} position={[0.231, 0.052, 0.629]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_310.geometry} material={materials.PaletteMaterial006} position={[0.231, 0.052, 0.629]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_346.geometry} material={materials['Material.071']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_348.geometry} material={materials['Material.071_0']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_354.geometry} material={materials['Material.071_1']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_358.geometry} material={materials['Material.071_2']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_364.geometry} material={materials['Material.071_3']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_366.geometry} material={materials['Material.071_4']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_380.geometry} material={materials['Material.071_5']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_392.geometry} material={materials['Material.071_6']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_402.geometry} material={materials['Material.071_7']} position={[0.231, 0.051, 0.629]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={0.143} />
      <mesh geometry={nodes.Object_1081.geometry} material={materials['Material.018_22']} position={[0.159, 0.063, 0.381]} rotation={[1.571, 1.493, -1.571]} scale={0.034} />
    </group>
  )
}

useGLTF.preload('/models/gaming-pc-transformed.glb')
